# Done to increase the memory available to gradle.
org.gradle.jvmargs = -Xmx3G
org.gradle.daemon = false
org.gradle.cache.cleanup = false

# Mod Properties
maven_group = me.aleksilassila
mod_id = litematica-printer
mod_name = Litematica Printer
mod_file_name = litematica-printer

# Mod Version
mod_version = 3.2.2-paths.2

# Dependencies (malilib / litematica)
malilib_version = 0.28.12
litematica_version = 0.27.14

# Minecraft, Fabric Loader and API and mappings versions
minecraft_version_out = 26.1.2
minecraft_version = 26.1.2

fabric_loader_version = 0.18.6
mod_menu_version = 18.0.0-alpha.8
fabric_api_version = 0.155.3+26.1.2
